version: '3.8'

services:
  db:
    build:
      context: ./database  # Asegúrate de que esta ruta sea correcta
      dockerfile: Dockerfile
    container_name: sql1
    hostname: sql1
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql:rw

  backend:
    container_name: my_backend_container
    build:
      context: ./backend  # Asegúrate de que esta ruta sea correcta
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - db
    ports:
      - "5002:8080"  # Mapear el puerto 5002 del host al puerto 8080 del contenedor

volumes:
  sqlserverdata:

